name: build android

on:
  push:
    branches: [demo]
  pull_request:
    branches: [demo]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        use_debug_libraries: [true, false]
        target_arch_abi: [armeabi-v7a, arm64-v8a, x86, x86_64]
    steps:
      - uses: actions/checkout@main
        with:
          submodules: 'recursive'
      - shell: bash
        run: |
          "${ANDROID_NDK_ROOT}/ndk-build" -C "./thirdparty/Brioche/build-android" "NDK_PROJECT_PATH:=null" "NDK_APPLICATION_MK:=./Application.mk" "APP_BUILD_SCRIPT:=./Android.mk" "NDK_OUT:=./debug_${{matrix.use_debug_libraries}}/obj" "NDK_LIBS_OUT:=./debug_${{matrix.use_debug_libraries}}/lib" "APP_DEBUG:=${{matrix.use_debug_libraries}}" "APP_ABI:=${{matrix.target_arch_abi}}" "APP_PLATFORM:=android-28" "APP_STL:=c++_static" -j$(nproc)
          "${ANDROID_NDK_ROOT}/ndk-build" -C "./thirdparty/Brioche-ImGui/thirdparty/freetype/build-android" "NDK_PROJECT_PATH:=null" "NDK_APPLICATION_MK:=./Application.mk" "APP_BUILD_SCRIPT:=./Android.mk" "NDK_OUT:=./debug_${{matrix.use_debug_libraries}}/obj" "NDK_LIBS_OUT:=./debug_${{matrix.use_debug_libraries}}/lib" "APP_DEBUG:=${{matrix.use_debug_libraries}}" "APP_ABI:=${{matrix.target_arch_abi}}" "APP_PLATFORM:=android-28" "APP_STL:=c++_static" -j$(nproc)
          make -C "./thirdparty/Brioche-ImGui/build-GLSL" -f "./GLSL.mk" "APP_DEBUG:=${{matrix.use_debug_libraries}}" -j$(nproc)
          "${ANDROID_NDK_ROOT}/ndk-build" -C "./thirdparty/Brioche-ImGui/build-android" "NDK_PROJECT_PATH:=null" "NDK_APPLICATION_MK:=./Application.mk" "APP_BUILD_SCRIPT:=./Android.mk" "NDK_OUT:=./debug_${{matrix.use_debug_libraries}}/obj" "NDK_LIBS_OUT:=./debug_${{matrix.use_debug_libraries}}/lib" "APP_DEBUG:=${{matrix.use_debug_libraries}}" "APP_ABI:=${{matrix.target_arch_abi}}" "APP_PLATFORM:=android-28" "APP_STL:=c++_static" -j$(nproc)
          make -C "./build-GLSL" -f "./GLSL.mk" "APP_DEBUG:=${{matrix.use_debug_libraries}}" -j$(nproc)
          "${ANDROID_NDK_ROOT}/ndk-build" -C "./build-android" "NDK_PROJECT_PATH:=null" "NDK_APPLICATION_MK:=./Application.mk" "APP_BUILD_SCRIPT:=./Android.mk" "NDK_OUT:=./debug_${{matrix.use_debug_libraries}}/obj" "NDK_LIBS_OUT:=./debug_${{matrix.use_debug_libraries}}/lib" "APP_DEBUG:=${{matrix.use_debug_libraries}}" "APP_ABI:=${{matrix.target_arch_abi}}" "APP_PLATFORM:=android-28" "APP_STL:=c++_static" -j$(nproc)
          make -C "./build-android" -f "./APK.mk" "ANDROID_SDK_DIR:=${ANDROID_SDK_ROOT}/." "JDK_DIR:=${JAVA_HOME}/." "ANDROID_SDK_BUILD_TOOLS_VERSION:=35.0.0" "APP_ABI:=${{matrix.target_arch_abi}}" "APP_DEBUG:=${{matrix.use_debug_libraries}}" "APP_PLATFORM:=android-35" -j$(nproc)
